version: 2.1

orbs:
  ruby: circleci/ruby@2.2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt-get install -y libnss3
      - run:
          name: Install Chrome WebDriver
          command: |
            sudo apt-get install -y chromium-driver
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.3-node
      - image: cimg/postgres:12.19
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: blog_test
          POSTGRES_PASSWORD: "password"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: "password"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Compile Assets
          command: bundle exec rails assets:precompile
      - ruby/rubocop-check
      - run:
          name: Test
          command: bundle exec rails test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
